#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X XI XII XIII XIV XV
#bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a vlc state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a "Microsoft Teams - Preview" desktop='^5'
bspc rule -a microsoft-edge desktop='^4'
bspc rule -a Microsoft-edge desktop='^4'
bspc rule -a Virt-manager desktop='^10'
bspc rule -a keepassxc state=floating
bspc rule -a KeePassXC state=floating
bspc rule -a gnome-calculator state=floating
bspc rule -a Gnome-calculator state=floating
bspc rule -a copyq state=floating
bspc rule -a Plank layer=above manage=on border=off

/home/dukercs/.local/bin/daily.py --setter feh

~/.config/polybar/launch.sh --hack1bar &

/usr/bin/plank &

/usr/bin/compton &

~/.config/conky/start.sh

bash ~/.fehbg &

/usr/bin/copyq &
/usr/bin/keepassxc &

bash -x ~/.config/bspwm/trabalho.sh > /tmp/bsplog.trabalho.sh 2>&1

/usr/bin/caffeine-indicator &

